apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "trustlink-indexer.fullname" . }}
  labels:
    {{- include "trustlink-indexer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "trustlink-indexer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "trustlink-indexer.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: indexer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "trustlink-indexer.fullname" . }}
            - secretRef:
                name: {{ include "trustlink-indexer.fullname" . }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
