apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trustlink-indexer.fullname" . }}
  labels:
    {{- include "trustlink-indexer.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ required "databaseUrl is required" .Values.databaseUrl | quote }}
